### ISSUE TITLE
Happy New Year,Abnerhqc！Can these codes work on windows10 instead of linux？

### ISSUE THREAD

**Issue by Wei-i** [AbnerHqC/GaitSet#24]
sincerely hope you can help me thanks!

**Comment by AbnerHqC** [comment]
Hi, happy new year! The codes haven't been tested on Windows. But the codes are mainly based on Pytorch0.4. So I guess if you can install python3 and pytorch0.4 or pytorch1.0 properly on windows10, the codes could work.

**Comment by 845603761** [comment]
Thanks for replying！Could I speak Chinese XD？ 2个星期前，我在win10系统的预处理程序成功了，但是在train.py中出现 CUDA runtime error（63）,OS call failed or operation not supported on this OS at C:\a\w\1\s\windows\pytorch\torch\csrc\generic\StorageSharing.cpp:232   然后我的CUDA 和CUDNN的版本也都一致，我之前下载的pytorch1.0也是这样 换成了pytorch0.4版本也不行， 非常的难过，请问ABnerhqc您 有处理的方法吗？

**Comment by 845603761** [comment]
本来我想尝试用下ubuntu系统，但是一些硬件问题 我装了双系统以后 ubuntu系统经常开机无法进入 加上我自己真的不太会用ubuntu o(╥﹏╥)o

- 

-

**Comment by AbnerHqC** [comment]
您好~请问您装完pytorch之后有进行简单的测试么？如果没有的话建议进行一些简单的测试，比如import torch然后新建一个矩阵并.cuda()之类。以确认pytorch和cuda等确实没有问题。因为您这个报错看起来像是cuda或者pytorch没装好。
预处理程序没有使用pytorch或是cuda，也没用到显卡，所以即便这俩没装好也是可以跑成功的。

**Comment by 845603761** [comment]
谢谢答复！您好，我有进行过import torch 以及 print(torch.cuda.is_available()) 以及print(torch.__version__) 结果都是成功的，我在pytorch官网上有搜索过这个error，当时我看到那里的负责人说这个是win10系统和CUDA的问题，与pytorch无关 他们也不懂为什么错误。

**Comment by AbnerHqC** [comment]
酱紫~不过我们这边没有win10的服务器，所以。。。很抱歉没法做相关的测试。希望这里有其他老师和同学能帮到您。

**Comment by 845603761** [comment]
嗯好的 ！我一开始在先决条件要求中没看到强调用哪个系统来搭建环境，以为用win10也可以，走了很多弯路：( 。再次感谢您在春节期间处理我的问题！

**Comment by erhahaha** [comment]
您好，我在Windows10上预处理一直没有成功，能和您问一下我所遇到的问题嘛？期待您的答复：

问题如下：在输出路径中建好了相对应的文件夹但是里面的是空的，报错如下：


ERROR OCCUR: PID ##%d##, ERRORTYPE: %s


 0 <class 'NotADirectoryError'>
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "E:\GaitSet\GaitSet-master\pretreatment.py", line 125, in cut_pickle
    frame_list = os.listdir(seq_path)
NotADirectoryError: [WinError 267] 目录名称无效。: 'E:\\GaitSet\\CASIA-B-TEST\\fyc\\00_1\\fyc-00_1-001.png'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pretreatment.py", line 193, in <module>
    raise e
  File "pretreatment.py", line 185, in <module>
    res.get(timeout=0.1)
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
NotADirectoryError: [Errno 20] 目录名称无效。: 'E:\\GaitSet\\CASIA-B-TEST\\fyc\\00_1\\fyc-00_1-001.png'

**Comment by 845603761** [comment]
我理解的是把config里面的数据集路径改一下就好 找一个空的文件夹设置一下路径就好～里面一开始就是空的


 
---Original---

**Comment by erhahaha** [comment]
感谢您的答复，解决了我的问题。
我在Windows10进行的调试，预处理之后，train报错如下（可能您没有会遇到这个问题，如果您了解这个问题，希望能得到您的答复，非常感谢！！）：
(tensorflow-gpu) E:\GaitSet\GaitSet-master>python train.py
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
THCudaCheck FAIL file=c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\torch\csrc\generic\StorageSharing.cpp line=232 error=71 : operation not supported
Traceback (most recent call last):
File "train.py", line 21, in 
m.fit()
File "E:\GaitSet\GaitSet-master\model\model.py", line 150, in fit
for seq, view, seq_type, label, batch_frame in train_loader:
File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 819, in iter
return _DataLoaderIter(self)
File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 560, in init
w.start()
File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\process.py", line 105, in start
self._popen = self._Popen(self)
File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\popen_spawn_win32.py", line 65, in init
reduction.dump(process_obj, to_child)
File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\multiprocessing\reductions.py", line 213, in reduce_tensor
(device, handle, storage_size_bytes, storage_offset_bytes) = storage.share_cuda()
RuntimeError: cuda runtime error (71) : operation not supported at c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\torch\csrc\generic\StorageSharing.cpp:232
(tensorflow-gpu) E:\GaitSet\GaitSet-master>Traceback (most recent call last):
File "", line 1, in 
File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
exitcode = _main(fd)
File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 115, in _main
self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by Summer-sss** [comment]
> 嗯好的！我一开始在先决条件要求中没看到看到使用该系统来建设环境，以为用win10也可以，走了很多弯路：(。再次感谢您在春节期间处理我的问题！

你好，请问你用win10运行出来了吗，我目前用win10出现了很多问题

**Comment by jiangSeu** [comment]
> 您好，我在Windows10上预处理一直没有成功，能和您问一下我所遇到的问题嘛？期待您的答复：
> 
> 问题如下：在输出路径中建好了相对应的文件夹但是里面的是空的，报错如下：
> 
> ERROR OCCUR: PID ##%d##, ERRORTYPE: %s
> 
> 0 <class 'NotADirectoryError'>
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\pool.py", line 119, in worker
> result = (True, func(*args, **kwds))
> File "E:\GaitSet\GaitSet-master\pretreatment.py", line 125, in cut_pickle
> frame_list = os.listdir(seq_path)
> NotADirectoryError: [WinError 267] 目录名称无效。: 'E:\GaitSet\CASIA-B-TEST\fyc\00_1\fyc-00_1-001.png'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "pretreatment.py", line 193, in
> raise e
> File "pretreatment.py", line 185, in
> res.get(timeout=0.1)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\pool.py", line 644, in get
> raise self._value
> NotADirectoryError: [Errno 20] 目录名称无效。: 'E:\GaitSet\CASIA-B-TEST\fyc\00_1\fyc-00_1-001.png'



> 感谢您的答复，解决了我的问题。
> 我在Windows10进行的调试，预处理之后，train报错如下（可能您没有会遇到这个问题，如果您了解这个问题，希望能得到您的答复，非常感谢！！）：
> (tensorflow-gpu) E:\GaitSet\GaitSet-master>python train.py
> Initialzing...
> Initializing data source...
> Loading training data...
> Data initialization complete.
> Initializing model...
> Model initialization complete.
> Training START
> THCudaCheck FAIL file=c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\torch\csrc\generic\StorageSharing.cpp line=232 error=71 : operation not supported
> Traceback (most recent call last):
> File "train.py", line 21, in
> m.fit()
> File "E:\GaitSet\GaitSet-master\model\model.py", line 150, in fit
> for seq, view, seq_type, label, batch_frame in train_loader:
> File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 819, in iter
> return _DataLoaderIter(self)
> File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 560, in init
> w.start()
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\process.py", line 105, in start
> self._popen = self._Popen(self)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\popen_spawn_win32.py", line 65, in init
> reduction.dump(process_obj, to_child)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\reduction.py", line 60, in dump
> ForkingPickler(file, protocol).dump(obj)
> File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\multiprocessing\reductions.py", line 213, in reduce_tensor
> (device, handle, storage_size_bytes, storage_offset_bytes) = storage.share_cuda()
> RuntimeError: cuda runtime error (71) : operation not supported at c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\torch\csrc\generic\StorageSharing.cpp:232
> (tensorflow-gpu) E:\GaitSet\GaitSet-master>Traceback (most recent call last):
> File "", line 1, in
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
> exitcode = _main(fd)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 115, in _main
> self = reduction.pickle.load(from_parent)
> EOFError: Ran out of input

Hello, I also met a similar problem. How did you solve this problem？ Thank you
